Minor fixes to TestSqlTaskExecution
1. Use legit TaskId in TestSqlTaskExecution

Previously "task-id" is used as TaskId, which is an invalid TaskId.
The tests passed but error will be thrown when tearing down drivers.

Example error message and stacktrace:

```
SEVERE Error destroying driver for task task-id
java.lang.IllegalArgumentException: Invalid taskId task-id
	at com.facebook.presto.spi.QueryId.checkArgument(QueryId.java:108)
	at com.facebook.presto.spi.QueryId.parseDottedId(QueryId.java:96)
	at com.facebook.presto.execution.TaskId.getStageId(TaskId.java:60)
	at com.facebook.presto.operator.OperatorContext.getOperatorStats(OperatorContext.java:441)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:788)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
	at com.facebook.presto.operator.DriverContext.getDriverStats(DriverContext.java:310)
	at com.facebook.presto.operator.PipelineContext.driverFinished(PipelineContext.java:179)
	at com.facebook.presto.operator.DriverContext.finished(DriverContext.java:175)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:519)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:683)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_null____20190213_192019_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

2. Acknowledge pages received in OutputBufferConsumer.consume.