Fix assertion messages in Tpch, Tpcds stat tests
Before the change, the tests would report something like

    java.lang.AssertionError: distinctValuesCount-s differ expected [false] but found [true]
    Expected :false
    Actual   :true

which is not clear -- `distinctValuesCount` is not a boolean.